### ISSUE TITLE
Bug when dragging

### ISSUE THREAD

**Issue by guidedways** [dagronf/DSFActionBar#1] opened 2021-02-18 13:34 UTC
In the demo app, when you drag  one of the buttons below the "Left Aligned" heading and release outside of the bar, the "dragging" cursor does not get reset.

**Comment by dagronf** [comment] 2021-02-18 22:48
Hey mate - thanks for the heads up! I was able to verify the issue and fix it. I pushed the fix just a few moments ago up to GitHub.

Can you please grab v1.0.0 (I just pushed it up to GitHub) and try that one out?  

Cheers and thanks!

**Comment by dagronf** [comment] 2021-04-11 02:43
Closed due to inactivity. Bug no longer reproducible.

**Closed as completed by dagronf** 2021-04-11 02:43 UTC
